### ISSUE TITLE
Enormously Insecure

### ISSUE THREAD

**Issue by ironfroggy** [Matthew-Dove/Inject#1]
This is in no way secure. Stripping style and script tags does not change that. Nothing else you do will likely change that. Please remove this repository before someone uses it.

At least put a very big, very bold, very red warning on it.

**Comment by Matthew-Dove** [comment]
Hey thanks for your feedback.
You're correct about the security concerns, the script and style tags are removed not for any XSS reason, but more to the tune that (at least right now), such tags aren't supported.

It was obvious to me that inline script will still run (such as onlick events), and non-relative images will load (so the external webserver can gather information about the user form the image request).

I didn't think to mention it, but you make a good point.
You should only use this when you don't expect the target to change it's content suddenly, and when you trust the source, or if trust is of no concern to you.

Thank you for your input, I will add an XSS warning to the readme file.
