### ISSUE TITLE
foundGarbage = document.body. ???

### ISSUE THREAD

**Issue by al-scvorets** [Matthew-Dove/Inject#3]
Hi,

Line 92

``` js
    var foundGarbage = document.body.getElementsByTagName(name);
```

Looks like it removes "garbages" from target document body, not from injectee.
Short synthetic example is [here](http://jsfiddle.net/al_scvorets/e8xb3gr4/).
It removes style for the red rectangle. 

Best regards,
Alexander

**Comment by Matthew-Dove** [comment]
Oh shoot, this must have been introduced when the code was refactored.

I'll have to fix this up, thanks for the heads up!

**Comment by Matthew-Dove** [comment]
This is now fixed, your jsfiddle example now contains style for red rectangle.
Appreciate the bug report, and your succinct example, you're a legend!
